version: '3.4'
networks:
  ntw_database:
    driver: bridge
  ntw_minio:
    driver: bridge
volumes:
  postgresql_data: 
  data1-1:
  data1-2:
  data2-1:
  data2-2:
services:
  database:
    image: postgres:12
    container_name: dbpolicia
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./ETAPA_1/database/conf/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./ETAPA_1/database/conf/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    restart: always
    environment:
      POSTGRES_USER: pjcmt
      POSTGRES_PASSWORD: 6tBXh*Eb
      POSTGRES_DB: dbpolicia
      PGDATA: /tmp
    networks:
      - ntw_database
  database-backup:
    build:
      context: ./ETAPA_1/database/backup/scripts
      dockerfile: ./../Dockerfile
    container_name: database-backup
    ports:
      - 5433:5433
    depends_on:
      - database
    restart: always
    environment:
      PGUSER: pjcmt
      PGPASSWORD: 6tBXh*Eb
      CRON_SCHEDULE: '0 2 * * *'
      DELETE_OLDER_THAN: 43200
      PGDB: dbpolicia
      PGHOST: dbpolicia
    volumes:
      - ./ETAPA_1/database/backup/files:/tmp/bkp
    command: dump-cron
    networks:
      - ntw_database
  pgadmin:
    image: dpage/pgadmin4:4
    container_name: dbadmin
    ports:
      - 16543:80
    networks:
      - ntw_database
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: geia@pjc.mt.gov.br
      PGADMIN_DEFAULT_PASSWORD: hXCmfR
  minio1:
    image: minio/minio:RELEASE.2021-01-08T21-18-21Z
    container_name: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: 5ZhUF9Qu
    command: server http://minio{1...2}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - ntw_database
      - ntw_minio
    depends_on:
      - database
  minio2:
    image: minio/minio:RELEASE.2021-01-08T21-18-21Z
    container_name: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: 5ZhUF9Qu
    command: server http://minio{1...2}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - ntw_database
      - ntw_minio
    depends_on:
      - database
  nginx:
    image: nginx:1.19.2-alpine
    container_name: nginx
    volumes:
      - ./ETAPA_1/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
    networks:
      - ntw_minio
    depends_on:
      - minio1
      - minio2         
  